### ISSUE TITLE
What about a automatic background change?

### ISSUE THREAD

**Issue by WebCrew** [GreenMeteor/humhub-outerlimits-theme#3]
**Is your feature request related to a problem? Please describe.**

No frustrations so far the theme is nice and the idea is good, BUT the "registration" at http://community.greenmeteor.pcriot.com is not working - I do not get any registration Email.

**Describe the solution you'd like**

What about a little JS script which allowes to have more as one background image changing every 10-15 sec? Could be also done with CSS I think.

**Describe alternatives you've considered**
Here is a example: https://stackoverflow.com/questions/21760208/dynamicly-changing-css-background-image

**Additional context**

No other context :)

Kind regards, Andy

**Comment by ArchBlood** [comment]
It's a good idea, although going through JS we'd have to make a completely custom background changer that's fit to HumHub's new JS approach, as for the email issue, we're working on this as we speak.

**Comment by WebCrew** [comment]
Sounds good :)

@Felli Here You can get absolutely free top level domains, so you do not have to work with subdomains :)
https://my.freenom.com/

**Comment by Felli** [comment]
Not really a priority, sorry. I use this domain to test HumHub modules that we create as well as themes.

**Comment by Felli** [comment]
Email registration should be back online.
